<?php

/**
 *
 * @author Alessandro Lanni
 */

namespace Alanni\PDO;


class AdvancedPDO extends \PDO
{

    const RW_CONNECTION = 'rw';
    const RO_CONNECTIONS = 'ro';

    private $connections = [];

    public function __construct($config)
    {
        $rwConnectionConfig = $config['rw'];

        if(!is_array($rwConnectionConfig))
            throw new \Exception('No RW connection defined');

        // Setup RW Connection
        $dsnRW = sprintf('%s:dbname=%s;host=%s', $config['driver'] , $rwConnectionConfig['dbname'], $rwConnectionConfig['host']);
        $this->connections[self::RW_CONNECTION] = new \PDO($dsnRW,$rwConnectionConfig['user'],$rwConnectionConfig['password']);

        if( is_array($config['ro']) && count($config['ro']) > 0 )
        {
            $this->connections[self::RO_CONNECTIONS] = [];
            foreach ($config['ro'] as $roConfig)
            {
                $dsnRO = sprintf('%s:dbname=%s;host=%s', $config['driver'] , $roConfig['dbname'], $roConfig['host']);
                $this->connections[self::RO_CONNECTIONS] = new \PDO($dsnRW,$roConfig['user'],$roConfig['password']);
            }
        }

        print_r($this->connections);
    }

    public function prepare($statement, array $driver_options = array())
    {

        parent::prepare($statement, $driver_options); // TODO: Change the autogenerated stub
    }
}